---
- name: Create path for maps
  file: path=/var/osm/ state=directory owner=root group=root mode=0644
  tags:
    - osm

- name: Download OSM map from Geofabrik
  sudo: yes
  shell: wget http://download.geofabrik.de/australia-oceania/new-zealand-latest.osm.pbf
  args:
    chdir: /var/osm/
    creates: /var/osm/new-zealand-latest.osm.pbf
  tags:
    - osm