---
- name: This playbook sets up NZOSS GIS Live DVD infrastructure
  hosts: all
  sudo: true
  sudo_user: root
  #roles:
  #- postgresql

  vars:
    postgresql_version: "9.4"
    postgresql_package_version: "9.4.*-1.pgdg14.04+1"

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart postgresql
    service: name=postgresql state=restarted

  roles:
    - locale
    - postgresql
    - mapserver
    - imposm
    - osm
    - basemaps