---
- name: This playbook sets up NZ OSM infrastructure with Vagrant
  hosts: vagrant
  sudo: true
  sudo_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - postgresql
    - mapserver
    - nginx
    - imposm
    - osm
    - basemaps

- name: This playbook sets up NZOSS GIS Live DVD infrastructure
  hosts: catalyst
  sudo: true
  sudo_user: root

  vars_files:
    - vars/default.yml

  roles:
    - locale
    - postgresql
    - mapserver
    - nginx
    - imposm
    - osm
    - basemaps
