- include: graphite.yml

- include: collectd.yml

- include: logstash.yml

- name: graphite container
  docker:
    name: graphite
    image: hopsoft/graphite-statsd
    state: running
    ports:
    - "8080:80"
    - "2003:2003"
    - "8125:8125/udp"
    #insecure_registry: true
  tags:
  - monitoring

